apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: buildah-
spec:
  serviceAccountName: buildah-service-account
  pipelineRef:
    name: buildah
  params:
    - name: image-repo
      value: docker pull quay.io/ophelia_huang/ophelia-kat-express:1
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce 
        resources:
          requests:
            storage: 1Gi