apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah
spec:
  params:
  - name: source-repo
    type: string
  - name: image-repo
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: "$(params.source-repo)"
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: pipeline-shared-data

  - name: build-image
    runAfter:
    - git-clone
    params:
    - name: IMAGE
      value: "$(params.image-repo):$(tasks.git-clone.results.commit)"
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  workspaces:
  - name: pipeline-shared-data