apiVersion: v1
kind: Secret
metadata:
  name: quay-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiM0JvWld4cFlWOW9kV0Z1Wnl0aWIyOTBZMkZ0Y0RwWE1VRkNVMWhZVjB0QlVFSk9ValZGUmxWSlZqTlZORGhXVlVoV1dUVllRME13VDFvNFIxQktRazlUUlUxSk4xbGFVRWRSTURORE5sQkpTVE16VWpFMiIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson