apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah
spec:
  params:
  - name: source-repo
    type: string
  - name: image-repo
    type: string
  - name: app-name
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: "$(params.source-repo)"
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: pipeline-shared-data

  - name: build-image
    runAfter:
    - git-clone
    params:
    - name: IMAGE
      value: "$(params.image-repo):$(tasks.git-clone.results.commit)"
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: pipeline-shared-data
  
  - name: create-configuration
    params:
      - name: app-name
        value: "$(params.app-name)"
      - name: source-repo
        value: "$(params.source-repo)"
      - name: commit
        value: "$(tasks.git-clone.results.commit)"
      - name: image-repo
        value: "$(params.image-repo)"
    runAfter:
      - build-image
    taskRef:
      name: create-configuration
    workspaces:
      - name: source
        workspace: pipeline-shared-data
  
  - name: deploy
    params:
      - name: manifest
        value: "$(tasks.create-configuration.results.manifest)"
      - name: app-namespace
        value: "$(context.pipelineRun.namespace)"
    runAfter:
      - create-configuration
    taskRef:
      name: deploy
    workspaces:
      - name: source
        workspace: pipeline-shared-data

  workspaces:
  - name: pipeline-shared-data