apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/main/task/npm/0.1/npm.yaml
- build-bot.ServiceAccount.yaml
- buildah.Pipeline.yaml
- buildah.Secret.yaml
